const levels = [
  ['Primaire', 'Cycle primaire'], ['1AC', '1ère année collège'], ['2AC', '2ème année collège'], ['3AC', '3ème année collège'], ['Tronc Commun', 'Lycée – tronc commun'], ['1BAC scientifique', 'Lycée – sciences'], ['1BAC lettres', 'Lycée – lettres'], ['2BAC', 'Lycée – deuxième année']
];
const subjectsByLevel = { Primaire:['Français','Mathématiques','Arabe'], '1AC':['Mathématiques','Français','Anglais','Physique-Chimie','SVT'], '2AC':['Mathématiques','Français','Anglais','Physique-Chimie','SVT'], '3AC':["Mathématiques", "Français", "Anglais", "Physique-Chimie", "SVT","Histoire-GEO","ARAB"], 'Tronc Commun':['Mathématiques','Français','Anglais','Physique-Chimie','SVT'], '1BAC scientifique':["Mathématiques", "Physique-Chimie", "SVT", "Français", "Arab", "Histoire-GEO", "Education islamique"], '1BAC lettres':['Français','Mathématiques'], '2BAC':['Physique-Chimie','Mathématiques','SVT','Anglais','Philosophie'] };
Object.assign(subjectsByLevel, JSON.parse(localStorage.getItem('nokhba-catalogue') || 'null') || window.NOKHBA_CATALOG || {});
const state = { step:1, level:'', subjects:[] };
const form = document.querySelector('#registration-form');
const screens = [...document.querySelectorAll('.screen')];
const error = () => document.querySelector(`.screen[data-step="${state.step}"] .form-error`);
const setError = message => error().textContent = message;
function showStep(step){ state.step = step; screens.forEach(s => s.classList.toggle('active', +s.dataset.step === step)); document.querySelectorAll('#steps li').forEach((li,i)=>li.classList.toggle('active',i < step)); document.querySelector('#progress-bar').style.width = `${(step-1)/3*100}%`; if(step === 3) renderSubjects(); if(step === 4) renderRecap(); window.scrollTo({top:0,behavior:'smooth'}); }
function renderLevels(){ document.querySelector('#levels').innerHTML = levels.map(([name,sub])=>`<button type="button" class="level-option ${state.level===name?'selected':''}" data-level="${name}">${name}<small>${sub}</small></button>`).join(''); }
function renderSubjects(){ const subjects = subjectsByLevel[state.level] || []; document.querySelector('#subjects-intro').textContent = `Niveau sélectionné : ${state.level}. Choisissez une ou plusieurs matières.`; document.querySelector('#subjects').innerHTML = subjects.map(name=>`<label class="subject-option ${state.subjects.includes(name)?'selected':''}"><input type="checkbox" value="${name}" ${state.subjects.includes(name)?'checked':''}><span><b>${name}</b><small>Disponible pour votre niveau</small></span></label>`).join(''); }
function renderRecap(){ const d = new FormData(form); const fullName = `${d.get('firstName')} ${d.get('lastName')}`; document.querySelector('#recap').innerHTML = `<div class="recap-section"><h3>Élève</h3><p><strong>${fullName}</strong></p><p>${d.get('studentPhone')} · ${d.get('school')}</p><p>${d.get('address')}</p></div><div class="recap-section"><h3>Niveau</h3><p><strong>${state.level}</strong></p></div><div class="recap-section"><h3>Matières choisies</h3>${state.subjects.map(x=>`<div class="subject-row"><span>${x}</span><span>✓</span></div>`).join('')}</div>`; }
function validate(){ setError(''); if(state.step===1){ const required = [...document.querySelectorAll('[data-step="1"] [required]')]; if(required.some(x=>!x.value.trim())){setError('Veuillez compléter tous les champs obligatoires.');return false;} } if(state.step===2&&!state.level){setError('Veuillez choisir votre niveau.');return false;} if(state.step===3&&!state.subjects.length){setError('Sélectionnez au moins une matière.');return false;} if(state.step===4&&!form.confirmed.checked){setError('Veuillez confirmer que vos informations sont correctes.');return false;} return true; }
document.addEventListener('click',e=>{ const next=e.target.closest('[data-next]'),back=e.target.closest('[data-back]'),level=e.target.closest('[data-level]'); if(level){state.level=level.dataset.level;state.subjects=[];renderLevels();return;} if(next&&validate())showStep(state.step+1); if(back)showStep(state.step-1); });
document.addEventListener('change',e=>{ if(e.target.matches('#subjects input')){ const n=e.target.value; state.subjects=e.target.checked?[...state.subjects,n]:state.subjects.filter(x=>x!==n); renderSubjects(); } });
document.querySelector('#submit-registration').addEventListener('click',async()=>{if(!validate())return; const d=new FormData(form); const code=`NOK-26-${String(Math.floor(Math.random()*90000)+10000)}`;const record={code,firstName:d.get('firstName'),lastName:d.get('lastName'),phone:d.get('studentPhone'),parentPhone:d.get('parentPhone'),school:d.get('school'),address:d.get('address'),level:state.level,subjects:state.subjects,status:'En attente',createdAt:new Date().toLocaleString('fr-FR')};try{if(window.NOKHBA_REMOTE.enabled)await window.NOKHBA_REMOTE.createRegistration(record);else window.NOKHBA_STORE.saveRegistration(record);}catch{setError('Une erreur est survenue. Veuillez réessayer.');return;}document.querySelector('#student-name').textContent=d.get('firstName');document.querySelector('#registration-code').textContent=code;form.hidden=true;document.querySelector('#success').hidden=false;document.querySelector('.progress-wrap').hidden=true;window.scrollTo({top:0,behavior:'smooth'});});
document.querySelector('#copy-code').addEventListener('click',async e=>{const code=document.querySelector('#registration-code').textContent;try{await navigator.clipboard.writeText(code);e.target.textContent='Code copié ✓';}catch{e.target.textContent=code;}setTimeout(()=>e.target.textContent='Copier le code',1800);});
document.querySelector('#new-registration').addEventListener('click',()=>{form.reset();state.level='';state.subjects=[];form.hidden=false;document.querySelector('#success').hidden=true;document.querySelector('.progress-wrap').hidden=false;renderLevels();showStep(1);});
renderLevels();
